stages:
  - build
  - deploy
#  - package

release-build:
  image: maven:3.5.2-jdk-8
  stage: build
  script: "mvn package -B -Dmaven.test.skip=true"
  artifacts:
    paths:
      - target/bill-server.jar
  only:
    - /^release-.*$/

release-deploy:
  stage: deploy
  script:
    - cp /home/bill/application.properties target
    - cd target
    - pgrep -l bill-server
    - pkill bill-server
    - nohup java -jar bill-server.jar &
  only:
    - /^release-.*$/
  tags:
    - mrtt

