image: maven:3.5.2-jdk-8

stages:
  - build
  - deploy
#  - package

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  # Generate the private/public key pair using:
  #
  #     ssh-keygen -f deploy_key -N ""
  #
  # then set the $SSH_PRIVATE_KEY environment variable in the CI (Travis-CI,
  # GitLab-CI, ...) to the base64 encoded private key:
  #
  #     cat deploy_key | base64 -w0
  #
  # and add the public key `deploy_key.pub` into the target git repository (with
  # write permissions).
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)

  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  - ssh-keyscan 119.28.1.107 >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts



release-build:
  stage: build
  script: "mvn package -B -Dmaven.test.skip=true"
  artifacts:
    paths:
      - target/bill-server.jar
  only:
    - /^release-.*$/

release-deploy:
  stage: deploy
  script:
    - scp target/bill-server.jar ubuntu@119.28.1.107:bill
    - ssh ubuntu@119.28.1.107 "cd bill; sh bill-start.sh"
  only:
    - /^release-.*$/

